#!/usr/bin/env python3
"""
Deepthought AI Server — Docker Compose Generator
=================================================
Generates:
  deepthought/docker-compose.yml   Ollama + OpenWebUI stack
  deepthought/setup.sh             Debian 13 bootstrap, P40-safe NVIDIA 550.x
                                   driver (proprietary, non-open), CUDA toolkit,
                                   NVIDIA Container Toolkit, Docker CE, dirs

Services
--------
  ollama       LLM inference server   port 11434   — singleton, default ON
  openwebui    Chat web interface      port 8080    — singleton, default ON

GPU notes
---------
  Tesla P40 (Pascal, sm_61) requires the PROPRIETARY driver flavor.
  The open-kernel flavor (nvidia-open-kernel-dkms) does NOT support Pascal.
  Debian 13 ships the 550.x series in non-free which is correct for P40.
  NVIDIA's own CUDA repo does not yet support Debian 13/Trixie, so we use
  Debian's nvidia-cuda-toolkit package instead.
"""

import os
import sys

OUTPUT_DIR = "deepthought"

# ──────────────────────────────────────────────────────────────────────────────
# Terminal helpers
# ──────────────────────────────────────────────────────────────────────────────

def clear():
    os.system("clear" if os.name == "posix" else "cls")

def header():
    print("\033[1;34m" + "=" * 60)
    print("    DEEPTHOUGHT AI SERVER — COMPOSE GENERATOR")
    print("=" * 60 + "\033[0m")
    print()

def section(title):
    pad = max(1, 55 - len(title))
    print(f"\n\033[1;33m── {title} \033[0m" + "─" * pad)

def success(msg):   print(f"\033[1;32m  ✓ {msg}\033[0m")
def info(msg):      print(f"\033[0;36m    {msg}\033[0m")
def warn(msg):      print(f"\033[0;33m  ⚠  {msg}\033[0m")

def prompt(msg, default=None):
    hint = f" [{default}]" if default is not None else ""
    try:
        val = input(f"\033[0;37m  {msg}{hint}: \033[0m").strip()
    except (EOFError, KeyboardInterrupt):
        print(); sys.exit(0)
    return val if val else default

def prompt_int(msg, lo=0, hi=99, default=0):
    while True:
        raw = prompt(msg, default)
        try:
            v = int(raw)
            if lo <= v <= hi:
                return v
            print(f"\033[1;31m    Enter a number between {lo} and {hi}\033[0m")
        except (ValueError, TypeError):
            print("\033[1;31m    Invalid number\033[0m")

def prompt_bool(msg, default=True):
    hint = "Y/n" if default else "y/N"
    raw = prompt(f"{msg} ({hint})", "").lower()
    if raw == "":
        return default
    return raw in ("y", "yes", "1", "true")

def pick_menu(title, options, default_idx=0):
    print(f"\n  {title}")
    for i, opt in enumerate(options, 1):
        marker = "  \033[0;32m←\033[0m" if i - 1 == default_idx else ""
        print(f"    \033[0;33m{i}\033[0m. {opt}{marker}")
    while True:
        raw = prompt(f"Select (1–{len(options)})", default_idx + 1)
        try:
            idx = int(raw) - 1
            if 0 <= idx < len(options):
                return idx
        except (ValueError, TypeError):
            pass
        print("\033[1;31m    Invalid choice\033[0m")


# ──────────────────────────────────────────────────────────────────────────────
# Config
# ──────────────────────────────────────────────────────────────────────────────

class Config:
    def __init__(self):
        self.ip                   = "10.50.0.14"
        self.ollama_enabled       = True
        self.openwebui_enabled    = True
        # GPU
        self.gpu_count            = 2          # default: dual P40
        # Ollama
        self.models_dir           = "/mnt/disk0/Deepthought/models"
        self.ollama_keep_alive    = "-1"       # keep loaded model in VRAM indefinitely
        self.ollama_num_parallel  = 1          # P40s aren't fast enough for >1 in parallel
        self.ollama_max_loaded    = 1          # one model resident at a time
        self.ollama_kv_cache      = "q8_0"    # halve KV VRAM cost on large models
        self.ollama_preload_model = ""         # optional: model to pin on startup
        # OpenWebUI
        self.openwebui_port       = 8080
        self.openwebui_data_dir   = "/mnt/disk0/Deepthought/openwebui"


# ──────────────────────────────────────────────────────────────────────────────
# Compose generators
# ──────────────────────────────────────────────────────────────────────────────

def gen_header(cfg):
    return f"""\
version: '3.8'
# ==============================================================================
# DEEPTHOUGHT AI SERVER — DOCKER COMPOSE
# Host: {cfg.ip}
# GPUs: {cfg.gpu_count}x Tesla P40 (Pascal, 24 GB VRAM each = {cfg.gpu_count * 24} GB total)
# Generated by generate_deepthought.py
#
# GPU NOTES:
#   - Both P40s are exposed to Ollama via "count: all"
#   - llama.cpp / Ollama will automatically split layers across both cards
#   - Set OLLAMA_SCHED_SPREAD=1 so layers are distributed evenly
#   - Pascal does NOT support flash attention — leave OLLAMA_FLASH_ATTENTION unset
#   - KV cache quantisation (q8_0) halves VRAM use for long contexts on 70B+ models
#   - OLLAMA_MAX_LOADED_MODELS=1 ensures only one model is resident;
#     set to 2 if you want a small always-hot model alongside a large one
#     (e.g. qwen3:4b ~3 GB + deepseek-r1:70b ~42 GB = 45 GB, fits in 48 GB)
# ==============================================================================

services:
"""


def gen_ollama(cfg):
    spread = (
        "      - OLLAMA_SCHED_SPREAD=1         "
        "# spread layers evenly across all GPUs\n"
    )

    preload_svc = ""
    if cfg.ollama_preload_model:
        m = cfg.ollama_preload_model
        preload_svc = f"""
  # ============================================================================
  # OLLAMA PRELOAD — pin {m} in VRAM on startup
  # ============================================================================
  ollama-preload:
    image: curlimages/curl:latest
    container_name: ollama-preload
    restart: "no"
    depends_on:
      - ollama
    entrypoint: >
      sh -c "
        echo 'Waiting for Ollama...';
        until curl -s http://ollama:11434 > /dev/null; do sleep 2; done;
        echo 'Preloading {m}...';
        curl -s -X POST http://ollama:11434/api/generate
          -d '{{\"model\": \"{m}\", \"prompt\": \"\", \"keep_alive\": -1}}';
        echo '{m} pinned in VRAM.';
      "
"""

    return f"""
  # ============================================================================
  # OLLAMA — LLM Inference Server
  #
  # Models are stored at: {cfg.models_dir}
  # Pull models with:  docker exec ollama ollama pull <model>
  #
  # Recommended large models for dual P40 (48 GB VRAM):
  #   deepseek-r1:70b-distill-q4_K_M   ~42 GB   reasoning model
  #   qwen2.5-coder:32b-instruct-q8_0  ~35 GB   code assistant
  #   hermes3:70b-instruct-q4_0        ~40 GB   general chat
  #   llama3.3:70b-instruct-q4_K_M     ~42 GB   general chat
  #   qwen3:4b-instruct                ~3 GB    fast small model
  # ============================================================================
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      # All pulled models land here — survives container rebuilds
      - {cfg.models_dir}:/root/.ollama/models
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE={cfg.ollama_keep_alive}
      - OLLAMA_NUM_PARALLEL={cfg.ollama_num_parallel}
      - OLLAMA_MAX_LOADED_MODELS={cfg.ollama_max_loaded}
      - OLLAMA_KV_CACHE_TYPE={cfg.ollama_kv_cache}
{spread}      # Pascal (P40) does NOT support flash attention.
      # Setting OLLAMA_FLASH_ATTENTION=1 silently falls back anyway, so omit it.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all              # expose BOTH P40s to Ollama
              capabilities: [gpu]
{preload_svc}"""


def gen_openwebui(cfg):
    return f"""
  # ============================================================================
  # OPEN WEBUI — Chat Interface + Model Switcher
  #
  # Access: http://{cfg.ip}:{cfg.openwebui_port}
  # First launch creates an admin account — set it up immediately.
  # ============================================================================
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "{cfg.openwebui_port}:8080"
    volumes:
      - {cfg.openwebui_data_dir}:/app/backend/data
    environment:
      # Point OpenWebUI at the Ollama container on the same Docker network
      - OPENAI_API_BASE_URL=http://ollama:11434/v1
      - OPENAI_API_KEY=sk-no-key-required
      # Enables the built-in Ollama integration (direct model management)
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
"""


# ──────────────────────────────────────────────────────────────────────────────
# Setup script
# ──────────────────────────────────────────────────────────────────────────────

def gen_setup_script(cfg):
    dirs = []
    if cfg.ollama_enabled:
        dirs.append(cfg.models_dir)
    if cfg.openwebui_enabled:
        dirs.append(cfg.openwebui_data_dir)

    # Add parent dirs
    all_dirs = set()
    for d in dirs:
        all_dirs.add(d)
        # ensure /mnt/disk0/Deepthought exists
        parts = d.split("/")
        for i in range(2, len(parts)):
            all_dirs.add("/".join(parts[:i]))

    mkdir_lines = "\n".join(f'  mkdir -p "{d}"' for d in sorted(all_dirs))

    preload_note = ""
    if cfg.ollama_preload_model:
        preload_note = f"""
# ── Pull preload model after stack is up ─────────────────────────────────────
section "Pulling preload model: {cfg.ollama_preload_model}"
echo -e "  ${{CYN}}If Ollama is already running, pulling now...${{RST}}"
if docker ps -q --filter name=ollama 2>/dev/null | grep -q .; then
  docker exec ollama ollama pull {cfg.ollama_preload_model} && \\
    log "Preload model {cfg.ollama_preload_model} pulled" || \\
    warn "Pull failed — run manually after stack starts: docker exec ollama ollama pull {cfg.ollama_preload_model}"
else
  warn "Ollama container not running yet."
  warn "After 'docker compose up -d' run:"
  warn "  docker exec ollama ollama pull {cfg.ollama_preload_model}"
fi
"""

    return f"""\
#!/usr/bin/env bash
# ==============================================================================
#  DEEPTHOUGHT AI SERVER — BOOTSTRAP SCRIPT
#  Target:   Debian 13 (Trixie)
#  Host IP:  {cfg.ip}
#  GPUs:     {cfg.gpu_count}x NVIDIA Tesla P40 (Pascal, 24 GB VRAM each)
#  Generated by generate_deepthought.py
#
#  !! P40 DRIVER NOTES !!
#  - Pascal GPUs require the PROPRIETARY driver (nvidia-kernel-dkms).
#  - The OPEN kernel flavor (nvidia-open-kernel-dkms) does NOT support Pascal.
#  - Debian 13 Trixie ships the 550.x series in non-free which works fine.
#  - NVIDIA's CUDA repo does not yet support Debian 13, so we use Debian's
#    own nvidia-cuda-toolkit package (CUDA 12.x, compatible with P40).
#  - Debian 13 kernel 6.12 requires linux-headers to be installed FIRST
#    or DKMS cannot build the kernel module.
#
#  Run as root:   sudo bash setup.sh
# ==============================================================================

set -euo pipefail
REBOOT_NEEDED=false

# ── Colours ───────────────────────────────────────────────────────────────────
RED="\\033[1;31m"; GRN="\\033[1;32m"; YEL="\\033[1;33m"
CYN="\\033[0;36m"; RST="\\033[0m";   BLD="\\033[1;37m"

log()     {{ echo -e "${{GRN}}  ✓ ${{RST}}$*"; }}
warn()    {{ echo -e "${{YEL}}  ⚠ ${{RST}}$*"; }}
err()     {{ echo -e "${{RED}}  ✗ ${{RST}}$*" >&2; exit 1; }}
section() {{ echo -e "\\n${{YEL}}── $* ${{RST}}${{CYN}}$(printf '%.0s─' {{1..40}})${{RST}}"; }}

[[ $EUID -ne 0 ]] && err "Run as root: sudo bash $0"

CALLING_USER="${{SUDO_USER:-$(whoami)}}"
CALLING_UID=$(id -u "$CALLING_USER" 2>/dev/null || echo 1000)
CALLING_GID=$(id -g "$CALLING_USER" 2>/dev/null || echo 1000)

echo ""
echo -e "${{BLD}}============================================================${{RST}}"
echo -e "${{BLD}}   DEEPTHOUGHT BOOTSTRAP — Debian 13 Trixie${{RST}}"
echo -e "${{BLD}}   {cfg.gpu_count}x Tesla P40 · 48 GB total VRAM${{RST}}"
echo -e "${{BLD}}============================================================${{RST}}"
echo ""

# ==============================================================================
# 1. ENABLE NON-FREE REPOS (required for NVIDIA drivers)
# ==============================================================================
section "Enabling non-free and contrib repositories"

SOURCES_FILE=/etc/apt/sources.list
if grep -q "non-free-firmware" "$SOURCES_FILE" 2>/dev/null; then
  log "non-free repos already enabled"
else
  # Append non-free components — no backreference needed
  sed -i '/trixie.*main$/s/$/ contrib non-free non-free-firmware/' "$SOURCES_FILE"
  sed -i '/trixie-security.*main$/s/$/ contrib non-free non-free-firmware/' "$SOURCES_FILE"
  log "non-free repos enabled in $SOURCES_FILE"
fi

# Also handle deb822-style sources if present
DEB822=/etc/apt/sources.list.d/debian.sources
if [ -f "$DEB822" ]; then
  if ! grep -q "non-free-firmware" "$DEB822"; then
    sed -i '/^Components:/ s/main$/main contrib non-free non-free-firmware/' "$DEB822"
    log "non-free repos enabled in $DEB822"
  fi
fi

apt-get update -qq

# ==============================================================================
# 2. SYSTEM UPDATE & BASE PACKAGES
# ==============================================================================
section "System update and base packages"

apt-get upgrade -y -qq
apt-get install -y -qq \\
  apt-transport-https \\
  ca-certificates \\
  curl \\
  wget \\
  gnupg \\
  lsb-release \\
  git \\
  jq \\
  htop \\
  nvtop \\
  iotop \\
  tmux \\
  vim \\
  nano \\
  pciutils \\
  usbutils \\
  net-tools \\
  dnsutils \\
  rsync \\
  unzip \\
  build-essential \\
  dkms \\
  software-properties-common
log "Base packages installed"

# ==============================================================================
# 3. KERNEL HEADERS (MUST come before NVIDIA driver on Debian 13 / kernel 6.12)
# ==============================================================================
section "Installing kernel headers"

KVER=$(uname -r)
apt-get install -y -qq "linux-headers-${{KVER}}" || \\
  apt-get install -y -qq linux-headers-amd64 || true
log "Kernel headers installed for ${{KVER}}"

# ==============================================================================
# 4. NVIDIA PROPRIETARY DRIVER — 550.x series (Pascal/P40 compatible)
#
#    IMPORTANT: We install nvidia-kernel-dkms (proprietary), NOT
#    nvidia-open-kernel-dkms.  Maxwell, Pascal, and Volta are explicitly
#    unsupported by the open flavor.
# ==============================================================================
section "Installing NVIDIA 550.x proprietary driver (P40 / Pascal)"

if lsmod 2>/dev/null | grep -q "^nvidia "; then
  DRV_VER=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null | head -1 || echo "unknown")
  log "NVIDIA driver already loaded (version: ${{DRV_VER}})"
  log "Skipping driver install — remove /etc/modprobe.d/nvidia-blacklist.conf"
  log "and run this section manually if you need a fresh install."
else
  warn "NVIDIA driver not loaded — installing 550.x proprietary series..."

  # Blacklist nouveau so it doesn't conflict
  cat > /etc/modprobe.d/blacklist-nouveau.conf << 'NOUVEAUEOF'
blacklist nouveau
options nouveau modeset=0
NOUVEAUEOF
  update-initramfs -u -k all 2>/dev/null || update-initramfs -u || true
  log "Nouveau blacklisted"

  # Install the proprietary DKMS kernel module + driver userspace
  # Do NOT use nvidia-open-kernel-dkms — Pascal is not supported.
  apt-get install -y -qq nvidia-kernel-dkms nvidia-driver
  log "nvidia-kernel-dkms + nvidia-driver installed"

  # Verify DKMS built correctly
  if dkms status 2>/dev/null | grep -q "nvidia.*installed"; then
    log "DKMS module build: OK"
  else
    warn "DKMS status unclear — check with: dkms status"
    warn "If not 'installed', run: dkms install nvidia/\$(dkms status | grep nvidia | cut -d, -f2 | tr -d ' ') -k \$(uname -r)"
  fi

  REBOOT_NEEDED=true
  warn "REBOOT REQUIRED to load the new NVIDIA kernel module."
fi

# ==============================================================================
# 5. NVIDIA CUDA TOOLKIT (Debian 13 native package — no CUDA repo needed)
#
#    CUDA repo does not yet support Debian 13/Trixie.
#    Debian's own nvidia-cuda-toolkit provides CUDA 12.x and is
#    fully compatible with the P40 (sm_61 compute capability).
# ==============================================================================
section "Installing NVIDIA CUDA toolkit (Debian 13 native package)"

if dpkg -l nvidia-cuda-toolkit 2>/dev/null | grep -q "^ii"; then
  log "nvidia-cuda-toolkit already installed"
else
  apt-get install -y -qq nvidia-cuda-toolkit
  log "nvidia-cuda-toolkit installed"
fi

# Symlink nvcc to PATH if not already there
if command -v nvcc &>/dev/null; then
  log "nvcc found at: $(command -v nvcc)"
else
  warn "nvcc not in PATH — it may be at /usr/lib/nvidia-cuda-toolkit/bin/nvcc"
  warn "Add to ~/.bashrc: export PATH=\$PATH:/usr/lib/nvidia-cuda-toolkit/bin"
fi

# ==============================================================================
# 6. DOCKER CE (Official Repo)
# ==============================================================================
section "Installing Docker CE"

for PKG in docker.io docker-doc docker-compose podman-docker containerd runc; do
  apt-get remove -y "$PKG" 2>/dev/null || true
done
log "Removed legacy docker packages (if any)"

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg \\
  | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

CODENAME=$(lsb_release -cs 2>/dev/null || echo "bookworm")
echo \\
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \\
  https://download.docker.com/linux/debian ${{CODENAME}} stable" \\
  > /etc/apt/sources.list.d/docker.list
apt-get update -qq

# Trixie may not yet be in Docker's repo — fall back to bookworm
if ! apt-cache show docker-ce &>/dev/null 2>&1; then
  warn "Docker repo has no packages for $CODENAME — using bookworm"
  echo \\
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \\
    https://download.docker.com/linux/debian bookworm stable" \\
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
fi

apt-get install -y -qq \\
  docker-ce \\
  docker-ce-cli \\
  containerd.io \\
  docker-buildx-plugin \\
  docker-compose-plugin

systemctl enable --now docker
log "Docker CE installed and started"

if ! groups "$CALLING_USER" | grep -q docker; then
  usermod -aG docker "$CALLING_USER"
  log "Added $CALLING_USER to docker group (re-login or 'newgrp docker' to apply)"
fi

# ==============================================================================
# 7. NVIDIA CONTAINER TOOLKIT
#    Enables 'deploy: resources: reservations: devices: nvidia' in compose.
#    This step must happen AFTER Docker is installed.
# ==============================================================================
section "Installing NVIDIA Container Toolkit"

if dpkg -l nvidia-container-toolkit 2>/dev/null | grep -q "^ii"; then
  log "nvidia-container-toolkit already installed"
else
  curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \\
    | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

  curl -fsSL https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \\
    | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \\
    > /etc/apt/sources.list.d/nvidia-container-toolkit.list

  apt-get update -qq
  apt-get install -y -qq nvidia-container-toolkit
  log "nvidia-container-toolkit installed"
fi

# Wire NVIDIA runtime into Docker
nvidia-ctk runtime configure --runtime=docker
systemctl restart docker
log "Docker configured with NVIDIA runtime (nvidia-ctk)"

# ==============================================================================
# 8. STORAGE — /mnt/disk0 check
# ==============================================================================
section "Checking /mnt/disk0 mount"

if mountpoint -q /mnt/disk0 2>/dev/null; then
  log "/mnt/disk0 is mounted"
elif [ -d /mnt/disk0 ]; then
  warn "/mnt/disk0 exists but is not a separate mount — using as local dir"
else
  mkdir -p /mnt/disk0
  warn "/mnt/disk0 created. Attach and mount your model disk here:"
  echo -e "  ${{CYN}}  UUID=<disk-uuid>  /mnt/disk0  ext4  defaults,nofail  0  2${{RST}}"
  echo -e "  Then: ${{CYN}}mount -a${{RST}}"
fi

# ==============================================================================
# 9. DIRECTORIES
# ==============================================================================
section "Creating Deepthought data directories"

{mkdir_lines}

chown -R "$CALLING_UID:$CALLING_GID" /mnt/disk0/Deepthought 2>/dev/null || true
log "Directories created, owned by $CALLING_USER"

# ==============================================================================
# 10. DOCKER DAEMON CONFIGURATION
# ==============================================================================
section "Configuring Docker daemon"

mkdir -p /etc/docker
if [ ! -f /etc/docker/daemon.json ]; then
  cat > /etc/docker/daemon.json << 'DAEMONEOF'
{{
  "log-driver": "json-file",
  "log-opts": {{
    "max-size": "20m",
    "max-file": "5"
  }},
  "storage-driver": "overlay2",
  "live-restore": true,
  "userland-proxy": false
}}
DAEMONEOF
  systemctl reload docker || systemctl restart docker
  log "Docker daemon config written"
else
  warn "/etc/docker/daemon.json already exists — skipping"
fi

# ==============================================================================
# 11. SYSCTL TUNING
# ==============================================================================
section "Applying sysctl tuning for LLM workloads"

cat > /etc/sysctl.d/99-deepthought.conf << 'SYSCTLEOF'
# Deepthought AI server tuning
vm.swappiness = 5
vm.overcommit_memory = 1        # allows llama.cpp large mmap allocations
vm.dirty_ratio = 20
vm.dirty_background_ratio = 5
net.core.somaxconn = 65535
net.ipv4.tcp_tw_reuse = 1
fs.inotify.max_user_watches = 524288
SYSCTLEOF
sysctl -p /etc/sysctl.d/99-deepthought.conf >/dev/null 2>&1 || true
log "sysctl tuning applied"

# ==============================================================================
# 12. WEEKLY DOCKER CLEANUP
# ==============================================================================
section "Installing weekly Docker cleanup cron"
cat > /etc/cron.weekly/docker-cleanup << 'CRONEOF'
#!/bin/bash
docker system prune -f --filter "until=168h" >> /var/log/docker-cleanup.log 2>&1
CRONEOF
chmod +x /etc/cron.weekly/docker-cleanup
log "Cron installed"
{preload_note}
# ==============================================================================
# GPU VERIFY
# ==============================================================================
section "GPU verification"

if command -v nvidia-smi &>/dev/null && ! $REBOOT_NEEDED; then
  echo ""
  nvidia-smi --query-gpu=index,name,memory.total,driver_version,compute_cap \\
             --format=csv,noheader 2>/dev/null \\
  | while IFS=',' read -r idx name vram drv cc; do
      echo -e "  ${{GRN}}GPU $idx${{RST}}  $(echo $name | xargs)  |  VRAM: $(echo $vram | xargs)  |  Driver: $(echo $drv | xargs)  |  CUDA cap: $(echo $cc | xargs)"
    done
  echo ""
  log "Both P40s should appear above. If only one shows, check PCI passthrough."
else
  warn "nvidia-smi not available yet (reboot pending or driver not loaded)."
  warn "After reboot, run:  nvidia-smi"
  warn "Expected:  2x Tesla P40 showing 24 GiB each."
fi

# ==============================================================================
# DONE
# ==============================================================================
echo ""
echo -e "${{GRN}}============================================================${{RST}}"
echo -e "${{GRN}}  Deepthought bootstrap complete!${{RST}}"
echo -e "${{GRN}}============================================================${{RST}}"
echo ""
if $REBOOT_NEEDED; then
  echo -e "  ${{RED}}╔══════════════════════════════════════════════╗${{RST}}"
  echo -e "  ${{RED}}║  REBOOT REQUIRED before starting containers  ║${{RST}}"
  echo -e "  ${{RED}}║  NVIDIA driver was installed via DKMS and    ║${{RST}}"
  echo -e "  ${{RED}}║  needs a full reboot to load the module.     ║${{RST}}"
  echo -e "  ${{RED}}╚══════════════════════════════════════════════╝${{RST}}"
  echo ""
  echo -e "  After reboot, verify GPUs:  ${{CYN}}nvidia-smi${{RST}}"
  echo ""
fi
echo -e "  ${{BLD}}Next steps:${{RST}}"
echo -e "  1. ${{CYN}}Reboot if prompted above${{RST}}"
echo -e "  2. ${{CYN}}Log out and back in${{RST}} (or run ${{CYN}}newgrp docker${{RST}})"
echo -e "  3. Start the stack:"
echo -e "     ${{CYN}}docker compose up -d${{RST}}"
echo -e "  4. Pull your first model:"
echo -e "     ${{CYN}}docker exec ollama ollama pull qwen3:4b-instruct${{RST}}"
echo -e "     ${{CYN}}docker exec ollama ollama pull deepseek-r1:70b-distill-q4_K_M${{RST}}"
echo -e "  5. Open WebUI:"
echo -e "     ${{CYN}}http://{cfg.ip}:{cfg.openwebui_port}${{RST}}"
echo -e "  6. Verify both P40s are used:"
echo -e "     Start a big model, then in another terminal:"
echo -e "     ${{CYN}}docker exec ollama nvidia-smi${{RST}}"
echo -e "     Both GPUs should show VRAM usage climbing."
echo ""
"""


# ──────────────────────────────────────────────────────────────────────────────
# DEPLOY.md
# ──────────────────────────────────────────────────────────────────────────────

def gen_deploy_md(cfg):
    preload_note = (
        f"\n# Pull preload model after stack is up:\n"
        f"#   docker exec ollama ollama pull {cfg.ollama_preload_model}\n"
        if cfg.ollama_preload_model else ""
    )
    return f"""\
# DEEPTHOUGHT AI SERVER — DEPLOYMENT INSTRUCTIONS
# Host: {cfg.ip}
# GPUs: {cfg.gpu_count}x Tesla P40 (Pascal, 24 GB VRAM each)
# Generated by generate_deepthought.py

## Quick start

# 1. Copy this folder to the server
#    scp -r deepthought/ {cfg.ip}:~/

# 2. Bootstrap (installs drivers, CUDA, Docker, NVIDIA Container Toolkit)
#    ssh {cfg.ip} "cd deepthought && sudo bash setup.sh"

# 3. REBOOT if prompted by the setup script (NVIDIA DKMS module needs it)
#    ssh {cfg.ip} "sudo reboot"

# 4. Start the stack
#    ssh {cfg.ip} "cd deepthought && docker compose up -d"

# 5. Pull models
#    docker exec ollama ollama pull qwen3:4b-instruct
#    docker exec ollama ollama pull deepseek-r1:70b-distill-q4_K_M
{preload_note}
## Services

  OpenWebUI:   http://{cfg.ip}:{cfg.openwebui_port}
  Ollama API:  http://{cfg.ip}:11434

## Configuration

  Models dir:     {cfg.models_dir}
  WebUI data dir: {cfg.openwebui_data_dir}
  Keep alive:     {cfg.ollama_keep_alive}   (-1 = indefinite)
  Max loaded:     {cfg.ollama_max_loaded}   model(s) in VRAM at once
  KV cache:       {cfg.ollama_kv_cache}

## Multi-model tip (OLLAMA_MAX_LOADED_MODELS=2)

  Total VRAM = {cfg.gpu_count * 24} GB.  Example combos that fit:
    qwen3:4b-instruct (~3 GB)  +  qwen2.5-coder:32b-instruct-q8_0 (~35 GB) = 38 GB ✓
    qwen3:4b-instruct (~3 GB)  +  deepseek-r1:70b-distill-q4_K_M  (~42 GB) = 45 GB ✓ (tight)
    qwen3:4b-instruct (~3 GB)  +  hermes3:70b-instruct-q4_0        (~40 GB) = 43 GB ✓
  If you want two models resident, set OLLAMA_MAX_LOADED_MODELS=2 in compose.

## Useful commands

# Verify both P40s are visible inside the container
#   docker exec ollama nvidia-smi

# List available models
#   docker exec ollama ollama list

# Run a model interactively
#   docker exec -it ollama ollama run deepseek-r1:70b-distill-q4_K_M

# Watch GPU usage while a model runs
#   watch -n1 'docker exec ollama nvidia-smi --query-gpu=index,memory.used,utilization.gpu --format=csv'

# Tail logs
#   docker compose logs -f ollama
#   docker compose logs -f openwebui

## Driver notes (P40 / Pascal)

  Driver series:  550.x (proprietary, from Debian 13 non-free)
  Open kernel:    NOT supported on Pascal — open kernel flavor (nvidia-open-kernel-dkms)
  Driver flavor:  nvidia-kernel-dkms (proprietary) — only this works on P40
  CUDA version:   12.x (via Debian's nvidia-cuda-toolkit, no CUDA repo needed)
  Flash attention: NOT supported on Pascal — leave OLLAMA_FLASH_ATTENTION unset
  Compute cap:    sm_61
"""


# ──────────────────────────────────────────────────────────────────────────────
# File generation
# ──────────────────────────────────────────────────────────────────────────────

def generate_files(cfg):
    orig_cwd = os.getcwd()
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.chdir(OUTPUT_DIR)
    out_abs = os.path.abspath(".")

    # docker-compose.yml
    parts = [gen_header(cfg)]
    if cfg.ollama_enabled:
        parts.append(gen_ollama(cfg))
    if cfg.openwebui_enabled:
        parts.append(gen_openwebui(cfg))

    with open("docker-compose.yml", "w") as f:
        f.write("".join(parts))
    success("Written: docker-compose.yml")

    # setup.sh
    with open("setup.sh", "w") as f:
        f.write(gen_setup_script(cfg))
    os.chmod("setup.sh", 0o755)
    success("Written: setup.sh")

    # DEPLOY.md
    with open("DEPLOY.md", "w") as f:
        f.write(gen_deploy_md(cfg))
    success("Written: DEPLOY.md")

    os.chdir(orig_cwd)

    print()
    print("\033[1;32m" + "=" * 60)
    print("  Deepthought files generated successfully!")
    print("=" * 60 + "\033[0m")
    print()
    print(f"  Output: \033[1;37m{out_abs}/\033[0m")
    print()
    print("  Next steps:")
    print(f"    1. \033[0;36mscp -r {OUTPUT_DIR}/ {cfg.ip}:~/\033[0m")
    print(f"    2. \033[0;36mssh {cfg.ip} 'cd {OUTPUT_DIR} && sudo bash setup.sh'\033[0m")
    print(f"    3. Reboot if prompted, then:")
    print(f"    4. \033[0;36mssh {cfg.ip} 'cd {OUTPUT_DIR} && docker compose up -d'\033[0m")
    print(f"    5. \033[0;36mhttp://{cfg.ip}:{cfg.openwebui_port}\033[0m")
    print()


# ──────────────────────────────────────────────────────────────────────────────
# Menu screens
# ──────────────────────────────────────────────────────────────────────────────

KV_OPTIONS = ["f16  — full precision (max VRAM)",
              "q8_0 — half VRAM, no quality loss (recommended)",
              "q4_0 — quarter VRAM, slight quality loss"]
KV_MAP     = ["f16", "q8_0", "q4_0"]


def screen_ip(cfg):
    clear(); header()
    section("Server IP Address")
    print()
    cfg.ip = prompt("Enter server IP", cfg.ip)
    success(f"IP set to {cfg.ip}")


def screen_services(cfg):
    clear(); header()
    section("Services")
    info("Toggle services on or off.")
    print()
    cfg.ollama_enabled     = prompt_bool("Enable Ollama (LLM server)?",      cfg.ollama_enabled)
    cfg.openwebui_enabled  = prompt_bool("Enable OpenWebUI (chat interface)?", cfg.openwebui_enabled)


def screen_gpu(cfg):
    clear(); header()
    section("GPU Configuration")
    info("This server has Tesla P40s (Pascal). The script always installs the")
    info("proprietary 550.x driver — the open kernel flavor does NOT support P40.")
    print()
    cfg.gpu_count = prompt_int("Number of P40 GPUs in this machine", 1, 8, cfg.gpu_count)
    total_vram = cfg.gpu_count * 24
    info(f"Total VRAM: {cfg.gpu_count} × 24 GB = {total_vram} GB")


def screen_paths(cfg):
    clear(); header()
    section("Storage Paths")
    info("All data stored under /mnt/disk0/Deepthought/ by default.")
    info("Models can be very large (70B q4 ≈ 42 GB, 70B q8 ≈ 80 GB).")
    print()
    cfg.models_dir = prompt(
        "Ollama models directory (where 'ollama pull' stores models)",
        cfg.models_dir
    )
    cfg.openwebui_data_dir = prompt(
        "OpenWebUI data directory",
        cfg.openwebui_data_dir
    )


def screen_ollama(cfg):
    if not cfg.ollama_enabled:
        return
    clear(); header()
    section("Ollama Options")
    print()
    cfg.ollama_keep_alive = prompt(
        "OLLAMA_KEEP_ALIVE (-1=indefinite, 0=unload after each request, 5m, 1h…)",
        cfg.ollama_keep_alive
    )
    cfg.ollama_max_loaded = prompt_int(
        "Max models resident in VRAM at once (1=safe, 2=multi-model)",
        1, 8, cfg.ollama_max_loaded
    )
    cfg.ollama_num_parallel = prompt_int(
        "Parallel inference requests (1 recommended for P40)",
        1, 16, cfg.ollama_num_parallel
    )
    default_kv = KV_MAP.index(cfg.ollama_kv_cache) if cfg.ollama_kv_cache in KV_MAP else 1
    ki = pick_menu("KV cache quantisation (saves VRAM on long contexts):", KV_OPTIONS, default_kv)
    cfg.ollama_kv_cache = KV_MAP[ki]
    print()
    info("Optional: model to pin in VRAM on container startup.")
    info("Example: qwen3:4b-instruct  (fast, low VRAM, good for always-on assistant)")
    info("Leave blank to skip.")
    cfg.ollama_preload_model = prompt("Preload model name", cfg.ollama_preload_model or "")


def screen_openwebui(cfg):
    if not cfg.openwebui_enabled:
        return
    clear(); header()
    section("OpenWebUI Options")
    print()
    cfg.openwebui_port = prompt_int(
        "OpenWebUI host port",
        1024, 65535, cfg.openwebui_port
    )
    info(f"OpenWebUI will be accessible at: http://{cfg.ip}:{cfg.openwebui_port}")


def show_summary(cfg):
    clear(); header()
    section("Configuration Summary")
    total_vram = cfg.gpu_count * 24
    print(f"\n  \033[0;37mHost IP:\033[0m     {cfg.ip}")
    print(f"  \033[0;37mGPUs:\033[0m        {cfg.gpu_count}x Tesla P40  ({total_vram} GB total VRAM)")
    print(f"  \033[0;37mDriver:\033[0m      550.x proprietary (from Debian 13 non-free)")
    print()
    print("  \033[1;37mServices:\033[0m")
    if cfg.ollama_enabled:
        print(f"    \033[1;32m✓\033[0m  Ollama        port 11434")
        print(f"           models dir:   {cfg.models_dir}")
        print(f"           keep_alive:   {cfg.ollama_keep_alive}")
        print(f"           max_loaded:   {cfg.ollama_max_loaded}")
        print(f"           kv_cache:     {cfg.ollama_kv_cache}")
        if cfg.ollama_preload_model:
            print(f"           preload:      {cfg.ollama_preload_model}")
    else:
        print(f"    \033[0;90m✗  Ollama        (disabled)\033[0m")

    if cfg.openwebui_enabled:
        print(f"    \033[1;32m✓\033[0m  OpenWebUI     port {cfg.openwebui_port}")
        print(f"           data dir:     {cfg.openwebui_data_dir}")
    else:
        print(f"    \033[0;90m✗  OpenWebUI     (disabled)\033[0m")
    print()


def main_menu(cfg):
    while True:
        clear(); header()
        total_vram = cfg.gpu_count * 24
        print("  \033[1;37mMain Menu\033[0m\n")
        print(f"    \033[0;33m1\033[0m.  Server IP             \033[0;36m{cfg.ip}\033[0m")
        print(f"    \033[0;33m2\033[0m.  Services              "
              f"Ollama={'on' if cfg.ollama_enabled else 'off'}  "
              f"OpenWebUI={'on' if cfg.openwebui_enabled else 'off'}")
        print(f"    \033[0;33m3\033[0m.  GPU count             "
              f"{cfg.gpu_count}x P40  ({total_vram} GB VRAM)")
        print(f"    \033[0;33m4\033[0m.  Storage paths")
        print(f"    \033[0;33m5\033[0m.  Ollama options")
        print(f"    \033[0;33m6\033[0m.  OpenWebUI options")
        print()
        print(f"    \033[0;33m7\033[0m.  Review summary")
        print(f"    \033[0;33m8\033[0m.  \033[1;32mGenerate files\033[0m")
        print(f"    \033[0;33m9\033[0m.  Quit")
        print()

        choice = prompt_int("Select option (1–9)", 1, 9, 8)

        if   choice == 1: screen_ip(cfg)
        elif choice == 2: screen_services(cfg)
        elif choice == 3: screen_gpu(cfg)
        elif choice == 4: screen_paths(cfg)
        elif choice == 5: screen_ollama(cfg)
        elif choice == 6: screen_openwebui(cfg)
        elif choice == 7:
            show_summary(cfg)
            prompt("Press Enter to continue", "")
        elif choice == 8:
            show_summary(cfg)
            print()
            if prompt_bool("Generate files now?", True):
                generate_files(cfg)
                return
        elif choice == 9:
            print("\n  Goodbye!\n")
            sys.exit(0)


# ──────────────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────────────

def main():
    cfg = Config()
    main_menu(cfg)

if __name__ == "__main__":
    main()
