#!/usr/bin/env bash
# ==============================================================================
#  DEEPTHOUGHT AI SERVER — BOOTSTRAP SCRIPT
#  Target:   Debian 13 (Trixie)
#  Host IP:  10.50.0.14
#  GPUs:     2x NVIDIA Tesla P40 (Pascal, 24 GB VRAM each)
#  Generated by generate_deepthought.py
#
#  !! P40 DRIVER NOTES !!
#  - Pascal GPUs require the PROPRIETARY driver (nvidia-kernel-dkms).
#  - The OPEN kernel flavor (nvidia-open-kernel-dkms) does NOT support Pascal.
#  - Debian 13 Trixie ships the 550.x series in non-free which works fine.
#  - NVIDIA's CUDA repo does not yet support Debian 13, so we use Debian's
#    own nvidia-cuda-toolkit package (CUDA 12.x, compatible with P40).
#  - Debian 13 kernel 6.12 requires linux-headers to be installed FIRST
#    or DKMS cannot build the kernel module.
#
#  Run as root:   sudo bash setup.sh
# ==============================================================================

set -euo pipefail
REBOOT_NEEDED=false

# ── Colours ───────────────────────────────────────────────────────────────────
RED="\033[1;31m"; GRN="\033[1;32m"; YEL="\033[1;33m"
CYN="\033[0;36m"; RST="\033[0m";   BLD="\033[1;37m"

log()     { echo -e "${GRN}  ✓ ${RST}$*"; }
warn()    { echo -e "${YEL}  ⚠ ${RST}$*"; }
err()     { echo -e "${RED}  ✗ ${RST}$*" >&2; exit 1; }
section() { echo -e "\n${YEL}── $* ${RST}${CYN}$(printf '%.0s─' {1..40})${RST}"; }

[[ $EUID -ne 0 ]] && err "Run as root: sudo bash $0"

CALLING_USER="${SUDO_USER:-$(whoami)}"
CALLING_UID=$(id -u "$CALLING_USER" 2>/dev/null || echo 1000)
CALLING_GID=$(id -g "$CALLING_USER" 2>/dev/null || echo 1000)

echo ""
echo -e "${BLD}============================================================${RST}"
echo -e "${BLD}   DEEPTHOUGHT BOOTSTRAP — Debian 13 Trixie${RST}"
echo -e "${BLD}   2x Tesla P40 · 48 GB total VRAM${RST}"
echo -e "${BLD}============================================================${RST}"
echo ""

# ==============================================================================
# 1. ENABLE NON-FREE REPOS (required for NVIDIA drivers)
# ==============================================================================
section "Enabling non-free and contrib repositories"

SOURCES_FILE=/etc/apt/sources.list
if grep -q "non-free-firmware" "$SOURCES_FILE" 2>/dev/null; then
  log "non-free repos already enabled"
else
  # Append non-free components — no backreference needed
  sed -i '/trixie.*main$/s/$/ contrib non-free non-free-firmware/' "$SOURCES_FILE"
  sed -i '/trixie-security.*main$/s/$/ contrib non-free non-free-firmware/' "$SOURCES_FILE"
  log "non-free repos enabled in $SOURCES_FILE"
fi

# Also handle deb822-style sources if present
DEB822=/etc/apt/sources.list.d/debian.sources
if [ -f "$DEB822" ]; then
  if ! grep -q "non-free-firmware" "$DEB822"; then
    sed -i '/^Components:/ s/main$/main contrib non-free non-free-firmware/' "$DEB822"
    log "non-free repos enabled in $DEB822"
  fi
fi

apt-get update -qq

# ==============================================================================
# 2. SYSTEM UPDATE & BASE PACKAGES
# ==============================================================================
section "System update and base packages"

apt-get upgrade -y -qq
apt-get install -y -qq \
  apt-transport-https \
  ca-certificates \
  curl \
  wget \
  gnupg \
  lsb-release \
  git \
  jq \
  htop \
  nvtop \
  iotop \
  tmux \
  vim \
  nano \
  pciutils \
  usbutils \
  net-tools \
  dnsutils \
  rsync \
  unzip \
  build-essential \
  dkms \
  software-properties-common
log "Base packages installed"

# ==============================================================================
# 3. KERNEL HEADERS (MUST come before NVIDIA driver on Debian 13 / kernel 6.12)
# ==============================================================================
section "Installing kernel headers"

KVER=$(uname -r)
apt-get install -y -qq "linux-headers-${KVER}" || \
  apt-get install -y -qq linux-headers-amd64 || true
log "Kernel headers installed for ${KVER}"

# ==============================================================================
# 4. NVIDIA PROPRIETARY DRIVER — 550.x series (Pascal/P40 compatible)
#
#    IMPORTANT: We install nvidia-kernel-dkms (proprietary), NOT
#    nvidia-open-kernel-dkms.  Maxwell, Pascal, and Volta are explicitly
#    unsupported by the open flavor.
# ==============================================================================
section "Installing NVIDIA 550.x proprietary driver (P40 / Pascal)"

if lsmod 2>/dev/null | grep -q "^nvidia "; then
  DRV_VER=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null | head -1 || echo "unknown")
  log "NVIDIA driver already loaded (version: ${DRV_VER})"
  log "Skipping driver install — remove /etc/modprobe.d/nvidia-blacklist.conf"
  log "and run this section manually if you need a fresh install."
else
  warn "NVIDIA driver not loaded — installing 550.x proprietary series..."

  # Blacklist nouveau so it doesn't conflict
  cat > /etc/modprobe.d/blacklist-nouveau.conf << 'NOUVEAUEOF'
blacklist nouveau
options nouveau modeset=0
NOUVEAUEOF
  update-initramfs -u -k all 2>/dev/null || update-initramfs -u || true
  log "Nouveau blacklisted"

  # Install the proprietary DKMS kernel module + driver userspace
  # Do NOT use nvidia-open-kernel-dkms — Pascal is not supported.
  apt-get install -y -qq nvidia-kernel-dkms nvidia-driver
  log "nvidia-kernel-dkms + nvidia-driver installed"

  # Verify DKMS built correctly
  if dkms status 2>/dev/null | grep -q "nvidia.*installed"; then
    log "DKMS module build: OK"
  else
    warn "DKMS status unclear — check with: dkms status"
    warn "If not 'installed', run: dkms install nvidia/\$(dkms status | grep nvidia | cut -d, -f2 | tr -d ' ') -k \$(uname -r)"
  fi

  REBOOT_NEEDED=true
  warn "REBOOT REQUIRED to load the new NVIDIA kernel module."
fi

# ==============================================================================
# 5. NVIDIA CUDA TOOLKIT (Debian 13 native package — no CUDA repo needed)
#
#    CUDA repo does not yet support Debian 13/Trixie.
#    Debian's own nvidia-cuda-toolkit provides CUDA 12.x and is
#    fully compatible with the P40 (sm_61 compute capability).
# ==============================================================================
section "Installing NVIDIA CUDA toolkit (Debian 13 native package)"

if dpkg -l nvidia-cuda-toolkit 2>/dev/null | grep -q "^ii"; then
  log "nvidia-cuda-toolkit already installed"
else
  apt-get install -y -qq nvidia-cuda-toolkit
  log "nvidia-cuda-toolkit installed"
fi

# Symlink nvcc to PATH if not already there
if command -v nvcc &>/dev/null; then
  log "nvcc found at: $(command -v nvcc)"
else
  warn "nvcc not in PATH — it may be at /usr/lib/nvidia-cuda-toolkit/bin/nvcc"
  warn "Add to ~/.bashrc: export PATH=\$PATH:/usr/lib/nvidia-cuda-toolkit/bin"
fi

# ==============================================================================
# 6. DOCKER CE (Official Repo)
# ==============================================================================
section "Installing Docker CE"

for PKG in docker.io docker-doc docker-compose podman-docker containerd runc; do
  apt-get remove -y "$PKG" 2>/dev/null || true
done
log "Removed legacy docker packages (if any)"

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg \
  | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

CODENAME=$(lsb_release -cs 2>/dev/null || echo "bookworm")
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
  https://download.docker.com/linux/debian ${CODENAME} stable" \
  > /etc/apt/sources.list.d/docker.list
apt-get update -qq

# Trixie may not yet be in Docker's repo — fall back to bookworm
if ! apt-cache show docker-ce &>/dev/null 2>&1; then
  warn "Docker repo has no packages for $CODENAME — using bookworm"
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/debian bookworm stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
fi

apt-get install -y -qq \
  docker-ce \
  docker-ce-cli \
  containerd.io \
  docker-buildx-plugin \
  docker-compose-plugin

systemctl enable --now docker
log "Docker CE installed and started"

if ! groups "$CALLING_USER" | grep -q docker; then
  usermod -aG docker "$CALLING_USER"
  log "Added $CALLING_USER to docker group (re-login or 'newgrp docker' to apply)"
fi

# ==============================================================================
# 7. NVIDIA CONTAINER TOOLKIT
#    Enables 'deploy: resources: reservations: devices: nvidia' in compose.
#    This step must happen AFTER Docker is installed.
# ==============================================================================
section "Installing NVIDIA Container Toolkit"

if dpkg -l nvidia-container-toolkit 2>/dev/null | grep -q "^ii"; then
  log "nvidia-container-toolkit already installed"
else
  curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
    | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

  curl -fsSL https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
    | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
    > /etc/apt/sources.list.d/nvidia-container-toolkit.list

  apt-get update -qq
  apt-get install -y -qq nvidia-container-toolkit
  log "nvidia-container-toolkit installed"
fi

# Wire NVIDIA runtime into Docker
nvidia-ctk runtime configure --runtime=docker
systemctl restart docker
log "Docker configured with NVIDIA runtime (nvidia-ctk)"

# ==============================================================================
# 8. STORAGE — /mnt/disk0 check
# ==============================================================================
section "Checking /mnt/disk0 mount"

if mountpoint -q /mnt/disk0 2>/dev/null; then
  log "/mnt/disk0 is mounted"
elif [ -d /mnt/disk0 ]; then
  warn "/mnt/disk0 exists but is not a separate mount — using as local dir"
else
  mkdir -p /mnt/disk0
  warn "/mnt/disk0 created. Attach and mount your model disk here:"
  echo -e "  ${CYN}  UUID=<disk-uuid>  /mnt/disk0  ext4  defaults,nofail  0  2${RST}"
  echo -e "  Then: ${CYN}mount -a${RST}"
fi

# ==============================================================================
# 9. DIRECTORIES
# ==============================================================================
section "Creating Deepthought data directories"

  mkdir -p "/mnt"
  mkdir -p "/mnt/disk0"
  mkdir -p "/mnt/disk0/Deepthought"
  mkdir -p "/mnt/disk0/Deepthought/models"
  mkdir -p "/mnt/disk0/Deepthought/openwebui"

chown -R "$CALLING_UID:$CALLING_GID" /mnt/disk0/Deepthought 2>/dev/null || true
log "Directories created, owned by $CALLING_USER"

# ==============================================================================
# 10. DOCKER DAEMON CONFIGURATION
# ==============================================================================
section "Configuring Docker daemon"

mkdir -p /etc/docker
if [ ! -f /etc/docker/daemon.json ]; then
  cat > /etc/docker/daemon.json << 'DAEMONEOF'
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "20m",
    "max-file": "5"
  },
  "storage-driver": "overlay2",
  "live-restore": true,
  "userland-proxy": false
}
DAEMONEOF
  systemctl reload docker || systemctl restart docker
  log "Docker daemon config written"
else
  warn "/etc/docker/daemon.json already exists — skipping"
fi

# ==============================================================================
# 11. SYSCTL TUNING
# ==============================================================================
section "Applying sysctl tuning for LLM workloads"

cat > /etc/sysctl.d/99-deepthought.conf << 'SYSCTLEOF'
# Deepthought AI server tuning
vm.swappiness = 5
vm.overcommit_memory = 1        # allows llama.cpp large mmap allocations
vm.dirty_ratio = 20
vm.dirty_background_ratio = 5
net.core.somaxconn = 65535
net.ipv4.tcp_tw_reuse = 1
fs.inotify.max_user_watches = 524288
SYSCTLEOF
sysctl -p /etc/sysctl.d/99-deepthought.conf >/dev/null 2>&1 || true
log "sysctl tuning applied"

# ==============================================================================
# 12. WEEKLY DOCKER CLEANUP
# ==============================================================================
section "Installing weekly Docker cleanup cron"
cat > /etc/cron.weekly/docker-cleanup << 'CRONEOF'
#!/bin/bash
docker system prune -f --filter "until=168h" >> /var/log/docker-cleanup.log 2>&1
CRONEOF
chmod +x /etc/cron.weekly/docker-cleanup
log "Cron installed"

# ── Pull preload model after stack is up ─────────────────────────────────────
section "Pulling preload model: qwen3:30b-a3b-q8_0"
echo -e "  ${CYN}If Ollama is already running, pulling now...${RST}"
if docker ps -q --filter name=ollama 2>/dev/null | grep -q .; then
  docker exec ollama ollama pull qwen3:30b-a3b-q8_0 && \
    log "Preload model qwen3:30b-a3b-q8_0 pulled" || \
    warn "Pull failed — run manually after stack starts: docker exec ollama ollama pull qwen3:30b-a3b-q8_0"
else
  warn "Ollama container not running yet."
  warn "After 'docker compose up -d' run:"
  warn "  docker exec ollama ollama pull qwen3:30b-a3b-q8_0"
fi

# ==============================================================================
# GPU VERIFY
# ==============================================================================
section "GPU verification"

if command -v nvidia-smi &>/dev/null && ! $REBOOT_NEEDED; then
  echo ""
  nvidia-smi --query-gpu=index,name,memory.total,driver_version,compute_cap \
             --format=csv,noheader 2>/dev/null \
  | while IFS=',' read -r idx name vram drv cc; do
      echo -e "  ${GRN}GPU $idx${RST}  $(echo $name | xargs)  |  VRAM: $(echo $vram | xargs)  |  Driver: $(echo $drv | xargs)  |  CUDA cap: $(echo $cc | xargs)"
    done
  echo ""
  log "Both P40s should appear above. If only one shows, check PCI passthrough."
else
  warn "nvidia-smi not available yet (reboot pending or driver not loaded)."
  warn "After reboot, run:  nvidia-smi"
  warn "Expected:  2x Tesla P40 showing 24 GiB each."
fi

# ==============================================================================
# DONE
# ==============================================================================
echo ""
echo -e "${GRN}============================================================${RST}"
echo -e "${GRN}  Deepthought bootstrap complete!${RST}"
echo -e "${GRN}============================================================${RST}"
echo ""
if $REBOOT_NEEDED; then
  echo -e "  ${RED}╔══════════════════════════════════════════════╗${RST}"
  echo -e "  ${RED}║  REBOOT REQUIRED before starting containers  ║${RST}"
  echo -e "  ${RED}║  NVIDIA driver was installed via DKMS and    ║${RST}"
  echo -e "  ${RED}║  needs a full reboot to load the module.     ║${RST}"
  echo -e "  ${RED}╚══════════════════════════════════════════════╝${RST}"
  echo ""
  echo -e "  After reboot, verify GPUs:  ${CYN}nvidia-smi${RST}"
  echo ""
fi
echo -e "  ${BLD}Next steps:${RST}"
echo -e "  1. ${CYN}Reboot if prompted above${RST}"
echo -e "  2. ${CYN}Log out and back in${RST} (or run ${CYN}newgrp docker${RST})"
echo -e "  3. Start the stack:"
echo -e "     ${CYN}docker compose up -d${RST}"
echo -e "  4. Pull your first model:"
echo -e "     ${CYN}docker exec ollama ollama pull qwen3:4b-instruct${RST}"
echo -e "     ${CYN}docker exec ollama ollama pull deepseek-r1:70b-distill-q4_K_M${RST}"
echo -e "  5. Open WebUI:"
echo -e "     ${CYN}http://10.50.0.14:8080${RST}"
echo -e "  6. Verify both P40s are used:"
echo -e "     Start a big model, then in another terminal:"
echo -e "     ${CYN}docker exec ollama nvidia-smi${RST}"
echo -e "     Both GPUs should show VRAM usage climbing."
echo ""
