#!/usr/bin/env python3
"""
Echo AI Server — Docker Compose Generator
==========================================
Generates:
  echo/docker-compose.yml   — Ollama + faster-whisper stack
  echo/setup.sh             — Debian 13 bootstrap:
                                NVIDIA 550.x proprietary driver (Pascal-safe)
                                NVIDIA CUDA toolkit (Debian native package)
                                NVIDIA Container Toolkit
                                Docker CE, directories, sysctl tuning
  echo/DEPLOY.md            — Deployment reference

Services
--------
  ollama          LLM inference server   port 11434  — singleton, default ON
  faster-whisper  Speech-to-text server  port 10300  — singleton, default ON

GPU notes (GTX 1080 Ti / Pascal, sm_61)
----------------------------------------
  NVIDIA confirmed R580 is the LAST driver branch supporting Pascal (GTX 10xx).
  590+ completely drops the 1080 Ti. Debian 13 ships the 550.x series in
  non-free which is still within the supported window and is correct.
  Same rules as the Tesla P40: MUST use nvidia-kernel-dkms (proprietary),
  NOT nvidia-open-kernel-dkms — Pascal is unsupported by the open flavor.
  CUDA 12.x (via Debian's nvidia-cuda-toolkit) is the last for Pascal.
  NVIDIA's CUDA repo does not yet support Debian 13/Trixie.
"""

import os
import sys

OUTPUT_DIR = "echo"

# ──────────────────────────────────────────────────────────────────────────────
# Terminal helpers
# ──────────────────────────────────────────────────────────────────────────────

def clear():
    os.system("clear" if os.name == "posix" else "cls")

def header():
    print("\033[1;35m" + "=" * 60)
    print("       ECHO AI SERVER — COMPOSE GENERATOR")
    print("=" * 60 + "\033[0m")
    print()

def section(title):
    pad = max(1, 55 - len(title))
    print(f"\n\033[1;33m── {title} \033[0m" + "─" * pad)

def success(msg):  print(f"\033[1;32m  ✓ {msg}\033[0m")
def info(msg):     print(f"\033[0;36m    {msg}\033[0m")
def warn(msg):     print(f"\033[0;33m  ⚠  {msg}\033[0m")

def prompt(msg, default=None):
    hint = f" [{default}]" if default is not None else ""
    try:
        val = input(f"\033[0;37m  {msg}{hint}: \033[0m").strip()
    except (EOFError, KeyboardInterrupt):
        print(); sys.exit(0)
    return val if val else default

def prompt_int(msg, lo=0, hi=99, default=0):
    while True:
        raw = prompt(msg, default)
        try:
            v = int(raw)
            if lo <= v <= hi:
                return v
            print(f"\033[1;31m    Enter a number between {lo} and {hi}\033[0m")
        except (ValueError, TypeError):
            print("\033[1;31m    Invalid number\033[0m")

def prompt_bool(msg, default=True):
    hint = "Y/n" if default else "y/N"
    raw = prompt(f"{msg} ({hint})", "").lower()
    if raw == "":
        return default
    return raw in ("y", "yes", "1", "true")

def pick_menu(title, options, default_idx=0):
    print(f"\n  {title}")
    for i, opt in enumerate(options, 1):
        marker = "  \033[0;32m←\033[0m" if i - 1 == default_idx else ""
        print(f"    \033[0;33m{i}\033[0m. {opt}{marker}")
    while True:
        raw = prompt(f"Select (1–{len(options)})", default_idx + 1)
        try:
            idx = int(raw) - 1
            if 0 <= idx < len(options):
                return idx
        except (ValueError, TypeError):
            pass
        print("\033[1;31m    Invalid choice\033[0m")


# ──────────────────────────────────────────────────────────────────────────────
# Config
# ──────────────────────────────────────────────────────────────────────────────

class Config:
    def __init__(self):
        self.ip                   = "10.50.0.20"
        self.ollama_enabled       = True
        self.whisper_enabled      = True
        self.gpu_driver           = "nvidia"   # "nvidia" or "none"
        self.gpu_count            = 1
        self.ollama_models_dir    = "/mnt/disk0/echo/ollama/models"
        self.ollama_keep_alive    = "-1"
        self.ollama_num_parallel  = 1
        self.ollama_max_loaded    = 1
        self.ollama_kv_cache      = "q8_0"
        self.ollama_preload_model = ""
        self.whisper_model        = "small-int8"
        self.whisper_lang         = "en"
        self.whisper_use_cuda     = True
        self.whisper_gpu_index    = 0


# ──────────────────────────────────────────────────────────────────────────────
# Compose fragment generators
# ──────────────────────────────────────────────────────────────────────────────

def gen_header(ip):
    return f"""\
version: '3.8'
# ==============================================================================
# ECHO AI SERVER — DOCKER COMPOSE
# Host: {ip}
# GPU:  GTX 1080 Ti (Pascal, sm_61, 11 GB VRAM)
# Generated by generate_echo.py
# ==============================================================================

services:
"""


def gen_ollama(cfg):
    if cfg.gpu_driver == "nvidia":
        gpu_block = """\
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
"""
        spread = ("      - OLLAMA_SCHED_SPREAD=1\n" if cfg.gpu_count > 1 else "")
    else:
        gpu_block = "    # No GPU — CPU-only mode\n"
        spread = ""

    preload_svc = ""
    if cfg.ollama_preload_model:
        m = cfg.ollama_preload_model
        preload_svc = f"""
  ollama-preload:
    image: curlimages/curl:latest
    container_name: ollama-preload
    restart: "no"
    depends_on:
      - ollama
    entrypoint: >
      sh -c "
        until curl -s http://ollama:11434 > /dev/null; do sleep 2; done;
        curl -s -X POST http://ollama:11434/api/generate
          -d '{{\"model\": \"{m}\", \"prompt\": \"\", \"keep_alive\": -1}}';
        echo '{m} pinned in VRAM.';
      "
"""

    return f"""
  # ============================================================================
  # OLLAMA — LLM Inference Server
  # Models dir: {cfg.ollama_models_dir}
  # GTX 1080 Ti has 11 GB VRAM. Recommended models:
  #   qwen3:4b-instruct                ~3 GB
  #   mistral:7b-instruct-q4_K_M       ~4 GB
  #   llama3.1:8b-instruct-q4_K_M      ~5 GB
  #   qwen2.5-coder:7b-instruct-q8_0   ~8 GB
  # ============================================================================
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - {cfg.ollama_models_dir}:/root/.ollama/models
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE={cfg.ollama_keep_alive}
      - OLLAMA_NUM_PARALLEL={cfg.ollama_num_parallel}
      - OLLAMA_MAX_LOADED_MODELS={cfg.ollama_max_loaded}
      - OLLAMA_KV_CACHE_TYPE={cfg.ollama_kv_cache}
{spread}      # Pascal (1080 Ti) does NOT support flash attention — leave unset.
{gpu_block}{preload_svc}"""


def gen_whisper(cfg):
    if cfg.gpu_driver == "nvidia" and cfg.whisper_use_cuda:
        runtime_line  = "    runtime: nvidia\n"
        cuda_env_line = f"      - CUDA_VISIBLE_DEVICES={cfg.whisper_gpu_index}\n"
        cuda_comment  = (
            f"  # Whisper on GPU {cfg.whisper_gpu_index} (CUDA). "
            "small-int8 uses ~1 GB VRAM — fits alongside Ollama on 11 GB.\n"
        )
    else:
        runtime_line  = "    # runtime: nvidia  # uncomment to enable GPU\n"
        cuda_env_line = "      # - CUDA_VISIBLE_DEVICES=0  # uncomment for GPU\n"
        cuda_comment  = "  # Whisper running on CPU.\n"

    return f"""
  # ============================================================================
  # FASTER-WHISPER — Speech-to-Text (Wyoming Protocol)
{cuda_comment}  # ============================================================================
  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
{runtime_line}    restart: unless-stopped
    ports:
      - "10300:10300"
    volumes:
      - /mnt/disk0/echo/whisper/models:/config/models
      - /mnt/disk0/echo/whisper/data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WHISPER_MODEL={cfg.whisper_model}
      - WHISPER_BEAM=1
      - WHISPER_LANG={cfg.whisper_lang}
{cuda_env_line}"""


# ──────────────────────────────────────────────────────────────────────────────
# Setup script
# ──────────────────────────────────────────────────────────────────────────────

def gen_setup_script(cfg):
    ip = cfg.ip

    dirs = ["/mnt/disk0/echo"]
    if cfg.ollama_enabled:
        dirs.append(cfg.ollama_models_dir)
    if cfg.whisper_enabled:
        dirs += ["/mnt/disk0/echo/whisper/models",
                 "/mnt/disk0/echo/whisper/data"]
    mkdir_lines = "\n".join(f'  mkdir -p "{d}"' for d in sorted(set(dirs)))

    gpu_mode_str = (
        f"NVIDIA CUDA ({cfg.gpu_count} GPU)" if cfg.gpu_driver == "nvidia"
        else "CPU-only"
    )

    if cfg.gpu_driver == "nvidia":
        nvidia_section = """\

# ==============================================================================
# 3. ENABLE NON-FREE REPOS (required for NVIDIA driver on Debian 13)
# ==============================================================================
section "Enabling non-free and contrib repositories"

SOURCES_FILE=/etc/apt/sources.list
if grep -q "non-free-firmware" "$SOURCES_FILE" 2>/dev/null; then
  log "non-free repos already enabled"
else
  sed -i '/trixie.*main$/s/$/ contrib non-free non-free-firmware/' "$SOURCES_FILE"
  sed -i '/trixie-security.*main$/s/$/ contrib non-free non-free-firmware/' "$SOURCES_FILE"
  log "non-free repos enabled in $SOURCES_FILE"
fi
DEB822=/etc/apt/sources.list.d/debian.sources
if [ -f "$DEB822" ] && ! grep -q "non-free-firmware" "$DEB822"; then
  sed -i '/^Components:/ s/main$/main contrib non-free non-free-firmware/' "$DEB822"
  log "non-free repos enabled in $DEB822"
fi
apt-get update -qq

# ==============================================================================
# 3a. KERNEL HEADERS — must come BEFORE the NVIDIA driver on Debian 13
#     Debian 13 kernel 6.12 does not ship headers by default.
#     DKMS will silently fail to build the module if headers are missing.
# ==============================================================================
section "Installing kernel headers"

KVER=$(uname -r)
apt-get install -y -qq "linux-headers-$KVER" || \\
  apt-get install -y -qq linux-headers-amd64 || true
log "Kernel headers installed for $KVER"

# ==============================================================================
# 3b. NVIDIA PROPRIETARY DRIVER — 550.x series (GTX 1080 Ti / Pascal, sm_61)
#
#  Driver selection rationale:
#  - NVIDIA confirmed R580 is the FINAL branch for Pascal/Maxwell/Volta.
#    590+ completely drops GTX 10xx (including the 1080 Ti).
#  - Debian 13 ships 550.x in non-free. Correct and within supported window.
#  - MUST install nvidia-kernel-dkms (proprietary flavor).
#    Do NOT use nvidia-open-kernel-dkms — Pascal is explicitly NOT supported
#    by the open-kernel flavor. Using it gives a silently broken install.
#  - CUDA 12.x via Debian native package. NVIDIA CUDA repo not on Trixie yet.
# ==============================================================================
section "Installing NVIDIA 550.x proprietary driver (GTX 1080 Ti / Pascal)"

if lsmod 2>/dev/null | grep -q "^nvidia "; then
  DRV_VER=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null | head -1 || echo "unknown")
  log "NVIDIA driver already loaded (version: $DRV_VER) — skipping install"
else
  warn "NVIDIA driver not loaded — installing 550.x proprietary series..."

  # Blacklist nouveau before the proprietary driver
  cat > /etc/modprobe.d/blacklist-nouveau.conf << 'NOUVEAUEOF'
blacklist nouveau
options nouveau modeset=0
NOUVEAUEOF
  update-initramfs -u -k all 2>/dev/null || update-initramfs -u || true
  log "Nouveau blacklisted and initramfs updated"

  # Install PROPRIETARY DKMS module + driver userspace.
  # Do NOT add nvidia-open-kernel-dkms here — Pascal not supported.
  apt-get install -y -qq nvidia-kernel-dkms nvidia-driver
  log "nvidia-kernel-dkms + nvidia-driver installed"

  if dkms status 2>/dev/null | grep -q "nvidia.*installed"; then
    log "DKMS module build: OK"
  else
    warn "DKMS status unclear — verify with: dkms status"
  fi

  REBOOT_NEEDED=true
  warn "REBOOT REQUIRED — new NVIDIA kernel module needs a full reboot to load."
fi

# ==============================================================================
# 3c. NVIDIA CUDA TOOLKIT (Debian 13 native — no CUDA repo needed)
#     NVIDIA CUDA repo not yet on Trixie. Debian's nvidia-cuda-toolkit gives
#     CUDA 12.x which is fully compatible with Pascal (sm_61). Last CUDA for Pascal.
# ==============================================================================
section "Installing NVIDIA CUDA toolkit (Debian 13 native)"

if dpkg -l nvidia-cuda-toolkit 2>/dev/null | grep -q "^ii"; then
  log "nvidia-cuda-toolkit already installed"
else
  apt-get install -y -qq nvidia-cuda-toolkit
  log "nvidia-cuda-toolkit installed (CUDA 12.x, compatible with sm_61)"
fi

# ==============================================================================
# 3d. NVIDIA CONTAINER TOOLKIT (must be installed AFTER Docker CE is running)
# ==============================================================================
section "Installing NVIDIA Container Toolkit"

if dpkg -l nvidia-container-toolkit 2>/dev/null | grep -q "^ii"; then
  log "nvidia-container-toolkit already installed"
else
  curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \\
    | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
  curl -fsSL https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \\
    | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \\
    > /etc/apt/sources.list.d/nvidia-container-toolkit.list
  apt-get update -qq
  apt-get install -y -qq nvidia-container-toolkit
  log "nvidia-container-toolkit installed"
fi

nvidia-ctk runtime configure --runtime=docker
systemctl restart docker
log "Docker configured with NVIDIA runtime (nvidia-ctk)"

echo ""
if command -v nvidia-smi &>/dev/null && ! $REBOOT_NEEDED; then
  nvidia-smi --query-gpu=index,name,memory.total,driver_version,compute_cap \\
             --format=csv,noheader 2>/dev/null \\
  | while IFS=',' read -r idx name vram drv cc; do
      echo -e "  ${GRN}GPU $idx${RST}  $(echo $name|xargs)  VRAM:$(echo $vram|xargs)  Driver:$(echo $drv|xargs)  Compute:$(echo $cc|xargs)"
    done || true
else
  warn "nvidia-smi not available yet (reboot pending or module not loaded)"
fi
"""
    else:
        nvidia_section = """\

# ==============================================================================
# 3. GPU (skipped — CPU-only mode selected)
# ==============================================================================
section "Skipping GPU drivers (CPU-only mode)"
warn "No GPU driver will be installed. Ollama and Whisper will run on CPU."
warn "To add GPU support later, re-run with GPU mode enabled."
"""

    preload_note = ""
    if cfg.ollama_enabled and cfg.ollama_preload_model:
        m = cfg.ollama_preload_model
        preload_note = f"""
# ── Pull preload model ────────────────────────────────────────────────────────
section "Pulling preload model: {m}"
if docker ps -q --filter name=ollama 2>/dev/null | grep -q .; then
  docker exec ollama ollama pull {m} && \\
    log "Model {m} pulled" || \\
    warn "Pull failed — run after stack: docker exec ollama ollama pull {m}"
else
  warn "Ollama not running yet. After 'docker compose up -d':"
  warn "  docker exec ollama ollama pull {m}"
fi
"""

    return f"""\
#!/usr/bin/env bash
# ==============================================================================
#  ECHO AI SERVER — BOOTSTRAP SCRIPT
#  Target:   Debian 13 (Trixie)
#  Host IP:  {ip}
#  GPU:      GTX 1080 Ti (Pascal sm_61, 11 GB VRAM)  —  {gpu_mode_str}
#  Generated by generate_echo.py
#
#  GTX 1080 Ti DRIVER NOTES:
#  - Pascal requires PROPRIETARY driver (nvidia-kernel-dkms)
#  - nvidia-open-kernel-dkms does NOT support Pascal — do not use it
#  - Debian 13 ships 550.x in non-free — correct and currently supported
#  - R580 is the final NVIDIA driver branch for Pascal; 590+ drops support
#  - CUDA 12.x is the last CUDA for Pascal (via Debian native package)
#
#  Run as root:  sudo bash setup.sh
# ==============================================================================

set -euo pipefail
REBOOT_NEEDED=false

# ── Colours & helpers ─────────────────────────────────────────────────────────
RED="\\033[1;31m"; GRN="\\033[1;32m"; YEL="\\033[1;33m"
CYN="\\033[0;36m"; RST="\\033[0m";   BLD="\\033[1;37m"

log()     {{ echo -e "${{GRN}}  ✓ ${{RST}}$*"; }}
warn()    {{ echo -e "${{YEL}}  ⚠ ${{RST}}$*"; }}
err()     {{ echo -e "${{RED}}  ✗ ${{RST}}$*" >&2; exit 1; }}
section() {{ echo -e "\\n${{YEL}}── $* ${{RST}}${{CYN}}$(printf '%.0s─' {{1..40}})${{RST}}"; }}

[[ $EUID -ne 0 ]] && err "Run as root: sudo bash $0"

CALLING_USER="${{SUDO_USER:-$(whoami)}}"
CALLING_UID=$(id -u "$CALLING_USER" 2>/dev/null || echo 1000)
CALLING_GID=$(id -g "$CALLING_USER" 2>/dev/null || echo 1000)

echo ""
echo -e "${{BLD}}============================================================${{RST}}"
echo -e "${{BLD}}       ECHO AI SERVER BOOTSTRAP — Debian 13 Trixie${{RST}}"
echo -e "${{BLD}}       Host: {ip}  |  {gpu_mode_str}${{RST}}"
echo -e "${{BLD}}============================================================${{RST}}"
echo ""

# ==============================================================================
# 1. SYSTEM UPDATE & BASE PACKAGES
# ==============================================================================
section "System update and base packages"

apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq \\
  apt-transport-https \\
  ca-certificates \\
  curl \\
  gnupg \\
  lsb-release \\
  wget \\
  git \\
  jq \\
  htop \\
  iotop \\
  nvtop \\
  tmux \\
  vim \\
  nano \\
  net-tools \\
  dnsutils \\
  pciutils \\
  usbutils \\
  smartmontools \\
  rsync \\
  unzip \\
  build-essential \\
  dkms \\
  software-properties-common
log "Base packages installed"

# ==============================================================================
# 2. DOCKER CE (Official Repo)
# ==============================================================================
section "Installing Docker CE"

for PKG in docker.io docker-doc docker-compose podman-docker containerd runc; do
  apt-get remove -y "$PKG" 2>/dev/null || true
done
log "Removed legacy docker packages (if any)"

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg \\
  | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

CODENAME=$(lsb_release -cs 2>/dev/null || echo "bookworm")
echo \\
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \\
  https://download.docker.com/linux/debian ${{CODENAME}} stable" \\
  > /etc/apt/sources.list.d/docker.list
apt-get update -qq

if ! apt-cache show docker-ce &>/dev/null 2>&1; then
  warn "Docker repo has no packages for $CODENAME — using bookworm"
  echo \\
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \\
    https://download.docker.com/linux/debian bookworm stable" \\
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
fi

apt-get install -y -qq \\
  docker-ce \\
  docker-ce-cli \\
  containerd.io \\
  docker-buildx-plugin \\
  docker-compose-plugin
systemctl enable --now docker
log "Docker CE installed and started"

if ! groups "$CALLING_USER" | grep -q docker; then
  usermod -aG docker "$CALLING_USER"
  log "Added $CALLING_USER to docker group"
fi
{nvidia_section}
# ==============================================================================
# 4. STORAGE — /mnt/disk0 check
# ==============================================================================
section "Checking /mnt/disk0 mount point"

if mountpoint -q /mnt/disk0 2>/dev/null; then
  log "/mnt/disk0 is mounted"
elif [ -d /mnt/disk0 ]; then
  warn "/mnt/disk0 exists but is not a separate mount"
else
  mkdir -p /mnt/disk0
  warn "/mnt/disk0 created. Mount your data disk here if needed."
fi

# ==============================================================================
# 5. DIRECTORIES
# ==============================================================================
section "Creating Echo data directories"

{mkdir_lines}

chown -R "$CALLING_UID:$CALLING_GID" /mnt/disk0/echo 2>/dev/null || true
log "Directories created, owned by $CALLING_USER"

# ==============================================================================
# 6. SYSCTL TUNING
# ==============================================================================
section "Applying sysctl tuning"

cat > /etc/sysctl.d/99-echo.conf << 'SYSCTLEOF'
# Echo AI server tuning
vm.swappiness = 10
vm.overcommit_memory = 1
net.core.somaxconn = 65535
net.ipv4.tcp_tw_reuse = 1
fs.inotify.max_user_watches = 524288
SYSCTLEOF
sysctl -p /etc/sysctl.d/99-echo.conf >/dev/null 2>&1 || true
log "sysctl tuning applied"

# ==============================================================================
# 7. DOCKER DAEMON CONFIG
# ==============================================================================
section "Configuring Docker daemon"

mkdir -p /etc/docker
if [ ! -f /etc/docker/daemon.json ]; then
  cat > /etc/docker/daemon.json << 'DAEMONEOF'
{{
  "log-driver": "json-file",
  "log-opts": {{
    "max-size": "20m",
    "max-file": "5"
  }},
  "storage-driver": "overlay2",
  "live-restore": true
}}
DAEMONEOF
  systemctl reload docker || systemctl restart docker
  log "Docker daemon config written"
else
  warn "/etc/docker/daemon.json already exists — skipping"
fi

# ==============================================================================
# 8. WEEKLY DOCKER CLEANUP
# ==============================================================================
section "Installing weekly Docker cleanup cron"
cat > /etc/cron.weekly/docker-cleanup << 'CRONEOF'
#!/bin/bash
docker system prune -f --filter "until=168h" >> /var/log/docker-cleanup.log 2>&1
CRONEOF
chmod +x /etc/cron.weekly/docker-cleanup
log "Cron installed"
{preload_note}
# ==============================================================================
# DONE
# ==============================================================================
echo ""
echo -e "${{GRN}}============================================================${{RST}}"
echo -e "${{GRN}}  Echo bootstrap complete!${{RST}}"
echo -e "${{GRN}}============================================================${{RST}}"
echo ""
if $REBOOT_NEEDED; then
  echo -e "  ${{RED}}╔════════════════════════════════════════════════╗${{RST}}"
  echo -e "  ${{RED}}║  REBOOT REQUIRED before starting containers   ║${{RST}}"
  echo -e "  ${{RED}}║  NVIDIA DKMS module needs a full reboot        ║${{RST}}"
  echo -e "  ${{RED}}╚════════════════════════════════════════════════╝${{RST}}"
  echo ""
fi
echo -e "  ${{BLD}}Next steps:${{RST}}"
echo -e "  1. ${{CYN}}Reboot if prompted above${{RST}}"
echo -e "  2. ${{CYN}}Re-login${{RST}} (or ${{CYN}}newgrp docker${{RST}})"
echo -e "  3. ${{CYN}}docker compose up -d${{RST}}"
echo -e "  4. ${{CYN}}docker exec ollama ollama pull qwen3:4b-instruct${{RST}}"
echo -e "  5. Ollama API:   ${{CYN}}http://{ip}:11434${{RST}}"
echo -e "  6. Whisper STT:  ${{CYN}}http://{ip}:10300${{RST}}"
echo ""
"""


# ──────────────────────────────────────────────────────────────────────────────
# DEPLOY.md
# ──────────────────────────────────────────────────────────────────────────────

def gen_deploy_md(cfg):
    services = []
    if cfg.ollama_enabled:
        services.append(f"  Ollama API:   http://{cfg.ip}:11434")
    if cfg.whisper_enabled:
        services.append(f"  Whisper STT:  http://{cfg.ip}:10300  (Wyoming protocol)")

    if cfg.gpu_driver == "nvidia":
        gpu_note = (
            f"  GPU:          GTX 1080 Ti (Pascal, sm_61) x{cfg.gpu_count}\n"
            f"  Driver:       550.x proprietary (Debian 13 non-free)\n"
            f"                R580 = last supported driver branch for Pascal\n"
            f"                590+ drops GTX 10xx entirely\n"
            f"  Open kernel:  NOT supported on Pascal — uses nvidia-kernel-dkms only\n"
            f"  CUDA:         12.x via Debian native nvidia-cuda-toolkit\n"
            f"  Flash attn:   NOT supported on Pascal (sm_61)\n"
            f"  Whisper GPU:  CUDA_VISIBLE_DEVICES={cfg.whisper_gpu_index}\n"
        )
    else:
        gpu_note = "  GPU mode:     CPU-only\n"

    preload_note = (
        f"\n# Pull preload model:\n"
        f"#   docker exec ollama ollama pull {cfg.ollama_preload_model}\n"
        if cfg.ollama_preload_model else ""
    )

    return f"""\
# ECHO AI SERVER — DEPLOYMENT INSTRUCTIONS
# Host: {cfg.ip}
# GPU:  GTX 1080 Ti (Pascal, sm_61, 11 GB VRAM)
# Generated by generate_echo.py

## Quick start

# 1. Copy this folder to the server
#    scp -r echo/ {cfg.ip}:~/

# 2. Bootstrap (installs 550.x driver, CUDA, Docker, Container Toolkit)
#    ssh {cfg.ip} "cd echo && sudo bash setup.sh"

# 3. REBOOT if the script says so (fresh NVIDIA DKMS install needs it)
#    ssh {cfg.ip} "sudo reboot"

# 4. Start the stack
#    ssh {cfg.ip} "cd echo && docker compose up -d"

# 5. Pull models (11 GB VRAM examples)
#    docker exec ollama ollama pull qwen3:4b-instruct
#    docker exec ollama ollama pull llama3.1:8b-instruct-q4_K_M
{preload_note}
## Services
{chr(10).join(services)}

## Configuration
{gpu_note}
  Models dir:    {cfg.ollama_models_dir}
  Whisper model: {cfg.whisper_model}
  Keep alive:    {cfg.ollama_keep_alive}
  KV cache:      {cfg.ollama_kv_cache}

## Useful commands

# Verify GPU inside Ollama container
#   docker exec ollama nvidia-smi

# Watch GPU while model runs
#   watch -n1 'docker exec ollama nvidia-smi --query-gpu=memory.used,utilization.gpu --format=csv'

# Tail logs
#   docker compose logs -f ollama
#   docker compose logs -f faster-whisper

# Check Whisper is reachable
#   nc -zv {cfg.ip} 10300
"""


# ──────────────────────────────────────────────────────────────────────────────
# File generation
# ──────────────────────────────────────────────────────────────────────────────

def generate_files(cfg):
    orig_cwd = os.getcwd()
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.chdir(OUTPUT_DIR)
    out_abs = os.path.abspath(".")

    parts = [gen_header(cfg.ip)]
    if cfg.ollama_enabled:
        parts.append(gen_ollama(cfg))
    if cfg.whisper_enabled:
        parts.append(gen_whisper(cfg))

    with open("docker-compose.yml", "w") as f:
        f.write("".join(parts))
    success("Written: docker-compose.yml")

    with open("setup.sh", "w") as f:
        f.write(gen_setup_script(cfg))
    os.chmod("setup.sh", 0o755)
    success("Written: setup.sh")

    with open("DEPLOY.md", "w") as f:
        f.write(gen_deploy_md(cfg))
    success("Written: DEPLOY.md")

    os.chdir(orig_cwd)

    print()
    print("\033[1;32m" + "=" * 60)
    print("  Echo files generated successfully!")
    print("=" * 60 + "\033[0m")
    print()
    print(f"  Output: \033[1;37m{out_abs}/\033[0m")
    print()
    print("  Next steps:")
    print(f"    1. \033[0;36mscp -r {OUTPUT_DIR}/ {cfg.ip}:~/\033[0m")
    print(f"    2. \033[0;36mssh {cfg.ip} 'cd {OUTPUT_DIR} && sudo bash setup.sh'\033[0m")
    print(f"    3. Reboot if prompted, then:")
    print(f"    4. \033[0;36mssh {cfg.ip} 'cd {OUTPUT_DIR} && docker compose up -d'\033[0m")
    print()


# ──────────────────────────────────────────────────────────────────────────────
# Menu screens
# ──────────────────────────────────────────────────────────────────────────────

WHISPER_MODELS = [
    "tiny", "tiny-int8", "base", "base-int8",
    "small", "small-int8", "medium", "medium-int8",
    "large-v2", "large-v3",
]
KV_OPTIONS = ["f16  — full precision (max VRAM)",
              "q8_0 — half VRAM, no quality loss (recommended)",
              "q4_0 — quarter VRAM, slight quality loss"]
KV_MAP = ["f16", "q8_0", "q4_0"]


def screen_ip(cfg):
    clear(); header(); section("Server IP Address"); print()
    cfg.ip = prompt("Enter server IP", cfg.ip)
    success(f"IP set to {cfg.ip}")


def screen_services(cfg):
    clear(); header(); section("Services"); print()
    cfg.ollama_enabled  = prompt_bool("Enable Ollama (LLM server)?",         cfg.ollama_enabled)
    cfg.whisper_enabled = prompt_bool("Enable faster-whisper (STT server)?", cfg.whisper_enabled)


def screen_gpu(cfg):
    clear(); header(); section("GPU Configuration")
    info("GTX 1080 Ti is Pascal (sm_61). The script installs the proprietary")
    info("550.x driver from Debian non-free — correct for Pascal.")
    info("nvidia-open-kernel-dkms is NOT supported on Pascal.")
    print()
    has_gpu = prompt_bool("Does this server have an NVIDIA GPU?", cfg.gpu_driver == "nvidia")
    if has_gpu:
        cfg.gpu_driver = "nvidia"
        cfg.gpu_count  = prompt_int("How many GPUs?", 1, 8, cfg.gpu_count)
    else:
        cfg.gpu_driver = "none"
        cfg.gpu_count  = 0
        cfg.whisper_use_cuda = False
        warn("CPU-only mode — inference will be significantly slower.")


def screen_ollama(cfg):
    if not cfg.ollama_enabled:
        return
    clear(); header(); section("Ollama Options")
    info("GTX 1080 Ti has 11 GB VRAM. Models up to ~8B q8 fit comfortably.")
    print()
    cfg.ollama_models_dir = prompt("Models directory on host", cfg.ollama_models_dir)
    cfg.ollama_keep_alive = prompt("OLLAMA_KEEP_ALIVE (-1=indefinite, 0=unload, 5m, 1h…)",
                                   cfg.ollama_keep_alive)
    cfg.ollama_max_loaded   = prompt_int("Max models in VRAM (1 recommended)", 1, 4,
                                         cfg.ollama_max_loaded)
    cfg.ollama_num_parallel = prompt_int("Parallel requests (1 recommended)", 1, 8,
                                          cfg.ollama_num_parallel)
    ki = pick_menu("KV cache quantisation:", KV_OPTIONS,
                   KV_MAP.index(cfg.ollama_kv_cache) if cfg.ollama_kv_cache in KV_MAP else 1)
    cfg.ollama_kv_cache = KV_MAP[ki]
    print()
    info("Optional: model name to pin in VRAM on startup. Leave blank to skip.")
    cfg.ollama_preload_model = prompt("Preload model name", cfg.ollama_preload_model or "")


def screen_whisper(cfg):
    if not cfg.whisper_enabled:
        return
    clear(); header(); section("Whisper STT Options")
    info("small-int8 (~1 GB VRAM) recommended — leaves plenty of room for Ollama.")
    print()
    mi = pick_menu("Whisper model:", WHISPER_MODELS,
                   WHISPER_MODELS.index(cfg.whisper_model)
                   if cfg.whisper_model in WHISPER_MODELS else 5)
    cfg.whisper_model = WHISPER_MODELS[mi]
    cfg.whisper_lang  = prompt("Language code (en, fr, de, auto…)", cfg.whisper_lang)
    if cfg.gpu_driver == "nvidia":
        cfg.whisper_use_cuda = prompt_bool("Run Whisper on GPU (CUDA)?", True)
        if cfg.whisper_use_cuda and cfg.gpu_count > 1:
            cfg.whisper_gpu_index = prompt_int(
                f"Which GPU index for Whisper? (0–{cfg.gpu_count-1})",
                0, cfg.gpu_count - 1, cfg.gpu_count - 1)
    else:
        cfg.whisper_use_cuda = False


def show_summary(cfg):
    clear(); header(); section("Configuration Summary")
    print(f"\n  \033[0;37mHost IP:\033[0m   {cfg.ip}")
    print(f"  \033[0;37mGPU:\033[0m       "
          + (f"NVIDIA {cfg.gpu_count}x GTX 1080 Ti  (550.x proprietary, Pascal)"
             if cfg.gpu_driver == "nvidia" else "CPU-only"))
    print()
    print("  \033[1;37mServices:\033[0m")
    if cfg.ollama_enabled:
        print(f"    \033[1;32m✓\033[0m  Ollama          port 11434")
        print(f"           models: {cfg.ollama_models_dir}")
        print(f"           kv: {cfg.ollama_kv_cache}  keep: {cfg.ollama_keep_alive}")
        if cfg.ollama_preload_model:
            print(f"           preload: {cfg.ollama_preload_model}")
    else:
        print(f"    \033[0;90m✗  Ollama          (disabled)\033[0m")
    if cfg.whisper_enabled:
        backend = f"GPU {cfg.whisper_gpu_index} (CUDA)" if cfg.whisper_use_cuda else "CPU"
        print(f"    \033[1;32m✓\033[0m  faster-whisper  port 10300")
        print(f"           model: {cfg.whisper_model}  lang: {cfg.whisper_lang}  backend: {backend}")
    else:
        print(f"    \033[0;90m✗  faster-whisper  (disabled)\033[0m")
    print()


def main_menu(cfg):
    while True:
        clear(); header()
        print("  \033[1;37mMain Menu\033[0m\n")
        print(f"    \033[0;33m1\033[0m.  Server IP             \033[0;36m{cfg.ip}\033[0m")
        print(f"    \033[0;33m2\033[0m.  Services              "
              f"Ollama={'on' if cfg.ollama_enabled else 'off'}  "
              f"Whisper={'on' if cfg.whisper_enabled else 'off'}")
        print(f"    \033[0;33m3\033[0m.  GPU configuration     "
              + (f"NVIDIA · {cfg.gpu_count}x 1080 Ti"
                 if cfg.gpu_driver == "nvidia" else "CPU-only"))
        print(f"    \033[0;33m4\033[0m.  Ollama options")
        print(f"    \033[0;33m5\033[0m.  Whisper options")
        print()
        print(f"    \033[0;33m6\033[0m.  Review summary")
        print(f"    \033[0;33m7\033[0m.  \033[1;32mGenerate files\033[0m")
        print(f"    \033[0;33m8\033[0m.  Quit")
        print()
        choice = prompt_int("Select option (1–8)", 1, 8, 7)
        if   choice == 1: screen_ip(cfg)
        elif choice == 2: screen_services(cfg)
        elif choice == 3: screen_gpu(cfg)
        elif choice == 4: screen_ollama(cfg)
        elif choice == 5: screen_whisper(cfg)
        elif choice == 6:
            show_summary(cfg)
            prompt("Press Enter to continue", "")
        elif choice == 7:
            show_summary(cfg)
            print()
            if prompt_bool("Generate files now?", True):
                generate_files(cfg)
                return
        elif choice == 8:
            print("\n  Goodbye!\n")
            sys.exit(0)


# ──────────────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────────────

def main():
    cfg = Config()
    main_menu(cfg)

if __name__ == "__main__":
    main()
